### ISSUE TITLE
Error: No asset found for platform linux-amd64 when using castor-php/setup-castor@v0.1.0

### ISSUE THREAD

**Issue by gponty** [castor-php/setup-castor#16]
Hello,

I encountered an error when using the following GitHub Actions configuration:

```
runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4

  - name: Setup Castor
    uses: castor-php/setup-castor@v0.1.0
```

Error Message:

`Error: No asset found for platform linux-amd64`

Is this issue coming from my script, or could it be a bug?

Thank you.

**Comment by pyrech** [comment]
Hi @gponty 

We had an issue on the release 0.18.1 of Castor, where assets were not attached to the release. We have already fixed it and released 0.18.2. Could you retry and ensure it's fixed with the github action using this latest release?

**Comment by gponty** [comment]
Thank you for your response.

Unfortunately, I'm still encountering an error when running the script:

```
Run castor-php/setup-castor@v0.1.0
  with:
    version: v0.18.2
    token: ***

Error: No asset found for platform linux-amd6
```

Do you have any idea what might be causing this issue?

Thank you in advance for your help.

**Comment by lyrixx** [comment]
Hello, We have worked hard on the releasing. It should not occurs anymore. Thanks for the report
